services:
  backend:
    build: .
    ports:
      - 8080:8080
    restart: always
    env_file:
      - .env
    environment:
      db-url: jdbc:postgresql://db:5432/${POSTGRES_DB}
    depends_on:
     - db
  db:
    image: postgres:16.2-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

volumes:
  db-data: